apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: s2i-spring-boot-camel
    component: concha-drum-lab
    group: quickstarts
    project: concha-drum-lab
    provider: s2i
    template: s2i-spring-boot-camel
    version: 1.0.0.redhat-000055
  name: concha-drum-lab
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: concha-drum-lab:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      env:
      - name: BUILD_LOGLEVEL
        value: "5"
      - name: ARTIFACT_DIR
      - name: MAVEN_ARGS
        value: package -DskipTests -Dfabric8.skip -e -B
      - name: MAVEN_ARGS_APPEND
      forcePull: true
      from:
        kind: ImageStreamTag
        name: fis-java-openshift:2.0
        namespace: openshift
      incremental: true
    type: Source
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange