apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: s2i-spring-boot-camel
    component: concha-drum-lab
    group: quickstarts
    project: concha-drum-lab
    provider: s2i
    template: s2i-spring-boot-camel
    version: 1.0.0.redhat-000055
  name: concha-drum-lab
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: concha-drum-lab
    deploymentconfig: concha-drum-lab
    group: quickstarts
    project: concha-drum-lab
    provider: s2i
    version: 1.0.0.redhat-000055
  sessionAffinity: None
  type: ClusterIP