apiVersion: v1
kind: Service
metadata:
  labels:
    app: "concha-drum-lab"
  name: "concha-drum-lab"
  namespace: "music-hack"
spec:
  ports:
  -
    name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: concha-drum-lab
    deploymentconfig: concha-drum-lab
  sessionAffinity: None
status:
  loadBalancer: {}
